name: Build my project

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PlatformIO
        run: |
          python3 -m pip install --user platformio

      - name: Build with PlatformIO
        run: |
          platformio run
